services:
  cadr.api:
    image: cadr.api
    container_name: cadr.api
    environment:
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
    build:
      context: .
      dockerfile: src/API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ${HOME}/.microsoft/usersecrets/:/home/app/.microsoft/usersecrets
      - ${HOME}/.aspnet/https/:/https/
      - ${HOME}/.aspnet/DataProtection-Keys/:/home/app/.aspnet/DataProtection-Keys

  cadr.database:
    image: postgres:latest
    container_name: cadr.database
    environment:
      - POSTGRES_DB=cadr
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/cadr.database:/var/lib/postgresql/data
    ports:
      - "5432:5432"