name: cadr.api
include:
  - docker-compose.services.yaml
services:
  cadr.api:
    depends_on:
      cadr.postgres:
        condition: service_healthy
      cadr.mailpit:
        condition: service_healthy
      cadr.azurite:
        condition: service_healthy
    build:
      context: ./
      dockerfile: api.Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - "8080:8080"
    networks:
      - cadr.network
